"""initial migration

Revision ID: 4532729c4539
Revises: dc6c5f64a0a
Create Date: 2016-09-27 19:11:19.376690

"""

# revision identifiers, used by Alembic.
revision = '4532729c4539'
down_revision = 'dc6c5f64a0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subposts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pid')
    )
    op.create_index('ix_subposts_timestamp', 'subposts', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subposts_timestamp', 'subposts')
    op.drop_table('subposts')
    ### end Alembic commands ###
